(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"181016_728x90_curvas_atlas_", frames: [[0,0,1000,403],[0,405,995,128],[539,535,389,253],[0,535,537,192]]}
];


// symbols:



(lib.Bitmap1 = function() {
	this.initialize(ss["181016_728x90_curvas_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap12 = function() {
	this.initialize(ss["181016_728x90_curvas_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap18 = function() {
	this.initialize(ss["181016_728x90_curvas_atlas_"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap8 = function() {
	this.initialize(ss["181016_728x90_curvas_atlas_"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Símbolo9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EFC672").s().p("APODKQgbgdAAg3IAAjrQAAg3AbgeQAbgdA2AAQA0AAAcAdQAbAeABA3IAADrQgBA3gbAdQgcAeg0AAQg2AAgbgegAQ6CdQAJgKABgYIAAj1QgBgYgJgLQgLgKgQABQgSgBgJAKQgKALAAAYIAAD1QAAAYAKAKQAJALASgBQAQABALgLgADBDKQgagdAAg3IAAjrQAAg3AageQAbgdA1AAQA1AAAbAdQAaAeAAA3IAAAsIhDAAIAAgxQgBgYgJgLQgKgKgRABQgSgBgJAKQgKALAAAYIAAD1QAAAYAKAKQAJAKASAAQARAAAKgKQAJgKABgYIAAhBIBDAAIAAA8QAAA3gaAdQgbAeg1AAQg1AAgbgegAS7DjIAAhFIBFAAIAABFgAKwDjIAAnFIBwAAQA1ABAbAcQAaAcAAA3IAADlQAAA3gaAcQgbAcg1ABgAL3CiIAoAAQARAAAKgJQAJgLAAgYIAAjrQAAgYgJgKQgKgLgRABIgoAAgAJFDjIgMhSIhYAAIgLBSIhCAAIBInFIBpAAIBIHFgAIvBTIgijlIgiDlIBEAAgAA8DjQgCgFgBgGIgCgQIgCgcIAAhIQAAgggLgNQgLgNgYAAIgYAAIAAC5IhHAAIAAnFIBrAAQA3AAAaAaQAYAaAAA1IAAAjQAAAjgLAXQgMAXgXAKQAaAMAKAYQAMAZgBAkIAABGQAAAQABAOQABAMAGANgAgRgWIAbAAQAVABAKgLQAMgLAAgaIAAgtQAAgZgJgLQgIgLgUAAIghAAgAlGDjIAAnFIDDAAIAABBIh8AAIAAB+IBiAAIAABAIhiAAIAACFIB8AAIAABBgAm9DjIAAlEIgyFEIhDAAIg2lAIAAFAIg+AAIAAnFIBjAAIA1FBIAwlBIBkAAIAAHFgAv3DjIAAnFIDCAAIAABBIh8AAIAAB+IBiAAIAABAIhiAAIAACFIB8AAIAABBgA0ADjIAAnFIBxAAQA1ABAbAcQAaAcAAA3IAADlQAAA3gaAcQgbAcg1ABgAy5CiIApAAQARAAAKgJQAJgLAAgYIAAjrQAAgYgJgKQgKgLgRABIgpAAgATDB/IgJikIAAi9IBHAAIAAC9IgJCkg");
	this.shape.setTransform(186.75,42.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo9, new cjs.Rectangle(58.7,19.6,256.2,46.49999999999999), null);


(lib.Símbolo8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EFC672").s().p("AMmDSQgWgZAAguIAAkkIA8AAIAAEnQAAAVAJAIQAHAJAPgBQAPABAIgJQAIgIABgVIAAknIA5AAIAAEkQAAAugYAZQgWAZgsAAQgtAAgXgZgAJRDSQgXgaAAguIAAjHQAAguAXgaQAWgYAtAAQAsAAAXAYQAXAaAAAuIAAAmIg5AAIAAgqQgBgUgHgJQgJgJgPABQgOgBgIAJQgJAJABAUIAADPQgBAUAJAJQAIAIAOAAQAPAAAJgIQAHgJABgUIAAg3IA5AAIAAAzQAAAugXAaQgXAYgsAAQgtAAgWgYgAF/DSQgXgaAAguIAAgYIA5AAIAAAcQAAAUAIAJQAJAIAPAAQAOAAAIgJQAIgIAAgUQAAgXgLgTQgMgRgRgPQgTgQgRgSQgRgRgMgWQgMgXgBghQAAguAXgaQAXgYAsAAQArAAAXAYQAWAaABAuIAAANIg6AAIAAgRQAAgUgHgJQgIgJgPABQgPgBgHAJQgIAJAAAUQAAAXAMATQAMARARAOIAjAiQASARALAXQAMAYABAgQAAAugXAaQgWAYgtAAQgsAAgXgYgAwuDSQgXgagBguIAAjHQABguAXgaQAYgYAsAAQAtAAAXAYQAXAaABAuIAADHQgBAugXAaQgXAYgtAAQgsAAgYgYgAvTCrQAIgJAAgUIAAjPQAAgUgIgJQgIgJgPABQgOgBgJAJQgIAJAAAUIAADPQAAAUAIAJQAJAJAOgBQAPABAIgJgAYNDmIgCgJQgCgGgBgJIgBgXIAAg8QAAgbgJgLQgJgMgVAAIgVAAIAACdIg8AAIAAl/IBbAAQAvAAAVAWQAWAWgBAtIAAAdQABAegKATQgKATgUAKQAWAJAJAVQAJAVAAAeIAAA8QAAANABALQABAMAFAKgAXLATIAXAAQASAAAJgJQAKgJAAgVIAAgmQAAgVgHgKQgIgJgPAAIgeAAgAU2DmIgKhGIhKAAIgLBGIg4AAIA+l/IBYAAIA+F/gAUjBsIgdjBIgdDBIA6AAgAQaDmIAAlIIg/AAIAAg3IC6AAIAAA3Ig/AAIAAFIgACpDmIAAl/ICkAAIAAA3IhpAAIAABqIBTAAIAAA2IhTAAIAABxIBpAAIAAA3gAh1DmIAAl/ICjAAIAAA3IhnAAIAABqIBSAAIAAA2IhSAAIAABxIBnAAIAAA3gAlVDmIAAl/IBfAAQAuABAWAYQAWAYAAAuIAADBQAAAugWAYQgWAYguABgAkZCvIAiAAQAPAAAIgIQAIgIAAgVIAAjHQAAgUgIgJQgIgIgPAAIgiAAgAoEDmIgKhGIhKAAIgKBGIg4AAIA+l/IBYAAIA9F/gAoXBsIgdjBIgcDBIA5AAgAroDmIgDgJQgCgGgBgJIgBgXIAAg8QAAgbgJgLQgJgMgVAAIgVAAIAACdIg8AAIAAl/IBbAAQAvAAAVAWQAWAWgBAtIAAAdQABAegKATQgKATgUAKQAWAJAJAVQAJAVAAAeIAAA8QAAANABALQABAMAFAKgAsrATIAXAAQASAAAJgJQAKgJAAgVIAAgmQAAgVgHgKQgIgJgPAAIgeAAgAyrDmIAAikIhEAAIAACkIg8AAIAAl/IA8AAIAACkIBEAAIAAikIA+AAIAAF/gA5JDmIAAl/ICkAAIAAA3IhoAAIAABqIBTAAIAAA2IhTAAIAABxIBoAAIAAA3gA4YitIAmg9IA6AAIg3A9g");
	this.shape.setTransform(176.7,21.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo8, new cjs.Rectangle(15.7,-1.6,322.1,47), null);


(lib.Símbolo6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D2F23").s().p("AHXCTQgOAAgJgEQgJgFgFgKQgGADgIABIgQACQgggBgRgRQgQgSgBgiIABiOQAAggAQgSQARgTAgABQAggBAQATQARASAAAgIAACOQAAAMgCAKQgCAJgEAIQABAEADABIAIABIAEAAIAAAmgAGEhlQgGAGAAAPIAACUQAAAOAGAGQAFAHALAAQAKAAAGgHQAGgGAAgOIAAiUQAAgPgGgGQgGgGgKAAIgBAAQgKAAgFAGgAjNCTQgOAAgJgEQgJgFgFgKQgGADgIABIgQACQgggBgRgRQgQgSgBgiIABiOQAAggAQgSQARgTAgABQAggBAQATQARASAAAgIAACOQAAAMgCAKQgCAJgEAIQABAEADABIAIABIAEAAIAAAmgAkghlQgGAGAAAPIAACUQAAAOAGAGQAFAHALAAQAKAAAGgHQAGgGAAgOIAAiUQAAgPgGgGQgGgGgKAAIgBAAQgKAAgFAGgAIAB0QgQgSAAghIAAjQIArAAIAADTQAAAOAGAHQAGAFAKABQAKgBAGgFQAGgHAAgOIAAjTIApAAIAADQQAAAhgQASQgQASggAAQggAAgQgSgAikB0QgQgSAAghIAAjQIArAAIAADTQAAAOAGAHQAGAFALABQAKgBAGgFQAGgHAAgOIAAjTIApAAIAADQQAAAhgRASQgQASggAAQggAAgQgSgAqoB0QgQgSAAgiIAAiOQAAggAQgSQAQgTAgABQAggBAQATQARASAAAgIAAAbIgpAAIAAgdQAAgPgGgGQgGgGgKAAQgLAAgGAGQgGAGAAAPIAACUQAAAOAGAGQAGAHALgBQAKABAGgHQAGgGAAgOIAAgoIApAAIAAAkQAAAigRASQgQARggABQgggBgQgRgAKNCDIAAkSIAsAAIAAESgAEWCDIgIgzIg1AAIgHAzIgoAAIAskSIA/AAIAsESgAEIAsIgUiLIgVCLIApAAgAgWCDIAAkSIB1AAIAAAnIhLAAIAABNIA7AAIAAAmIg7AAIAABQIBLAAIAAAogAmYCDIAAkSIArAAIAAESgAodCDIAAkSIArAAIAADqIBHAAIAAAog");
	this.shape.setTransform(75.075,26.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0D2F23").s().p("AHXCTQgOAAgJgEQgJgFgFgKQgGADgIABIgQACQgggBgRgRQgQgSgBgiIABiOQAAggAQgSQARgTAgABQAggBAQATQARASAAAgIAACOQAAAMgCAKQgCAJgEAIQABAEADABIAIABIAEAAIAAAmgAGEhlQgGAGAAAPIAACUQAAAOAGAGQAFAHALAAQAKAAAGgHQAGgGAAgOIAAiUQAAgPgGgGQgGgGgKAAIgBAAQgKAAgFAGgAjNCTQgOAAgJgEQgJgFgFgKQgGADgIABIgQACQgggBgRgRQgQgSgBgiIABiOQAAggAQgSQARgTAgABQAggBAQATQARASAAAgIAACOQAAAMgCAKQgCAJgEAIQABAEADABIAIABIAEAAIAAAmgAkghlQgGAGAAAPIAACUQAAAOAGAGQAFAHALAAQAKAAAGgHQAGgGAAgOIAAiUQAAgPgGgGQgGgGgKAAIgBAAQgKAAgFAGgAIAB0QgQgSAAghIAAjQIArAAIAADTQAAAOAGAHQAGAFAKABQAKgBAGgFQAGgHAAgOIAAjTIApAAIAADQQAAAhgQASQgQASggAAQggAAgQgSgAikB0QgQgSAAghIAAjQIArAAIAADTQAAAOAGAHQAGAFALABQAKgBAGgFQAGgHAAgOIAAjTIApAAIAADQQAAAhgRASQgQASggAAQggAAgQgSgAqoB0QgQgSAAgiIAAiOQAAggAQgSQAQgTAgABQAggBAQATQARASAAAgIAAAbIgpAAIAAgdQAAgPgGgGQgGgGgKAAQgLAAgGAGQgGAGAAAPIAACUQAAAOAGAGQAGAHALgBQAKABAGgHQAGgGAAgOIAAgoIApAAIAAAkQAAAigRASQgQARggABQgggBgQgRgAKNCDIAAkSIAsAAIAAESgAEWCDIgIgzIg1AAIgHAzIgoAAIAskSIA/AAIAsESgADfAsIApAAIgUiLgAgWCDIAAkSIB1AAIAAAnIhLAAIAABNIA7AAIAAAmIg7AAIAABQIBLAAIAAAogAmYCDIAAkSIArAAIAAESgAodCDIAAkSIArAAIAADqIBHAAIAAAog");
	this.shape_1.setTransform(75.275,26.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape,p:{x:75.075}}]}).to({state:[{t:this.shape,p:{x:75.275}}]},9).to({state:[]},1).to({state:[{t:this.shape_1}]},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,145,41.4);


(lib.Símbolo5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.instance = new lib.Bitmap12();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.3079,0.3079);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo5, new cjs.Rectangle(0,0,306.4,39.4), null);


(lib.Símbolo4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.instance = new lib.Bitmap8();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.3287,0.3287);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo4, new cjs.Rectangle(0,0,176.5,63.1), null);


(lib.Símbolo3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.instance = new lib.Bitmap18();
	this.instance.parent = this;
	this.instance.setTransform(-5,-1,0.2548,0.2548);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo3, new cjs.Rectangle(-5,-1,99.1,64.5), null);


(lib.Símbolo2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EFC672").s().p("A7QCtQgQAAgMgGQgKgFgFgLQgIADgJABIgTACQglAAgUgVQgMgMgFgVQgDgMAAgPIAAinQABgnATgVQAUgVAlAAQAmAAATAVQAHAIAFAKQAIARAAAZIAACMIAAAbQAAANgDAMQgCANgFAHQACAFADABQADABAGAAIAFAAIAAAtgA8MBoQAHgIAAgRIAAgeIAAiPQAAgRgHgIQgGgHgNAAQgLAAgHAGIgBABQgGAHgBASIAACtQABASAGAHQAHAIAMgBQAMABAHgIgA6gCJQgTgWAAgmIAAgcIAAi2IAAgjIAzAAIAAAjIAAC2IAAAfQAAAQAHAIQAHAHAMAAQANAAAHgHQAFgHABgRIAAgfIAAi2IAAgjIAwAAIAAAjIAAC2IAAAcQAAAmgTAWQgTAUglABQgmgBgTgUgAbiCZIAAhoIAAi2IAAgjICLAAIAAAjIAAALIhYAAIAABaIBGAAIAAAtIhGAAIAAAkIAAA6IBYAAIAAAugAYmCZIAAhoIAAi2IAAgjIBQAAQAnAAASAUQAGAHAFAIQAIASAAAaIAACKIAAAZQAAAmgTAVQgSAUgnAAgAZZAxIAAA6IAcAAQANAAAHgHQAGgGAAgSIAAgbIAAiMQAAgSgGgGQgHgHgNAAIgcAAgAXOCZIgchoIgiiAIAACAIAABoIgvAAIAAhoIAAi2IAAgjIBAAAIAKAjIAqCdIAAidIAAgjIAtAAIAAAjIAAC2IAABogAS5CZIAAhoIAAi2IAAgjICKAAIAAAjIAAALIhXAAIAABaIBFAAIAAAtIhFAAIAAAkIAAA6IBXAAIAAAugAQ7CZIAAhoIAAirIg0AAIAAgLIAAgjICcAAIAAAjIAAALIg1AAIAACrIAABogAO8CZIgchoIgjiAIAACAIAABoIguAAIAAhoIAAi2IAAgjIBAAAIAKAjIAqCdIAAidIAAgjIAtAAIAAAjIAAC2IAABogAKnCZIAAhoIAAi2IAAgjICKAAIAAAjIAAALIhYAAIAABaIBGAAIAAAtIhGAAIAAAkIAAA6IBYAAIAAAugAG2CZIAAhoIAAi2IAAgjICKAAIAAAjIAAALIhXAAIAABaIBFAAIAAAtIhFAAIAAAkIAAA6IBXAAIAAAugAE5CZIAAhoIAAirIg1AAIAAgLIAAgjICcAAIAAAjIAAALIg0AAIAACrIAABogAC6CZIgchoIgjiAIAACAIAABoIguAAIAAhoIAAi2IAAgjIBAAAIAJAjIArCdIAAidIAAgjIAtAAIAAAjIAAC2IAABogAhbCZIAAhoIAAi2IAAgjICKAAIAAAjIAAALIhXAAIAABaIBFAAIAAAtIhFAAIAAAkIAAA6IBXAAIAAAugAiwCZIAAhoIAAh+IgTB+IgPBoIgwAAIgShoIgUh7IAAB7IAABoIgtAAIAAhoIAAi2IAAgjIBHAAIAGAjIAeC2IABALIACgLIAci2IAFgjIBGAAIAAAjIAAC2IAABogAnxCZIAAhoIAAi2IAAgjIAzAAIAAAjIAAC2IAAA6IBTAAIAAAugAo8CZIgIg6Ig+AAIgJA6IgvAAIARhoIAdi2IAGgjIBKAAIAGAjIAdC2IAQBogAp8AxIAAACIAxAAIAAgCIgZiggAtWCZIAAhoIAAi2IAAgjICKAAIAAAjIAAALIhXAAIAABaIBFAAIAAAtIhFAAIAAAkIAAA6IBXAAIAAAugAulCZQgBgCgBgFIgCgMIgBhHIgBgOQgCgMgFgGQgIgJgRAAIgSAAIAAAbIAABoIgyAAIAAhoIAAi2IAAgjIBMAAQAoAAARASQAHAHAFAKQAHAQgBAXIAAAZQAAAagIAQQgIAQgQAIQAOAGAIALIADAHQAGANACAPIAAAPIABBHQAAAIAFAKgAvdgXIAUAAQAPAAAIgHQAIgIAAgTIAAggQAAgRgGgIQgHgIgNAAIgZAAgAysCZIAAhoIAAh+IgTB+IgQBoIgwAAIgRhoIgVh7IAAB7IAABoIgsAAIAAhoIAAi2IAAgjIBHAAIAFAjIAeC2IACALIACgLIAbi2IAFgjIBHAAIAAAjIAAC2IAABogA36CZIAAhoIAAi2IAAgjICKAAIAAAjIAAALIhXAAIAABaIBGAAIAAAtIhGAAIAAAkIAAA6IBXAAIAAAug");
	this.shape.setTransform(166.225,31.575);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo2, new cjs.Rectangle(-23.8,14.3,380.1,34.599999999999994), null);


(lib.Símbolo_7_Camada_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABJA0QgCgBgBgEIAAgBIAJAAIAAABIAAACIACAAIACAAIABgCIgBgCIgDgBIgBAAIAAgGQgIAAgDgFQgEgFAAgJIAAgmQAAgJAFgFQAEgFAIAAQAKAAAEAFQAFAFgBAJIAAAHIgLAAIAAgIQAAgEgBgCQgBAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAABAAAAQgCACAAAEIAAAoQAAAEACACQAAAAAAABQABAAAAAAQABABABAAQAAAAABAAQABAAAAAAQABAAABgBQAAAAABAAQAAgBABAAQABgCAAgEIAAgLIALAAIAAAKQAAAJgDAFQgEAFgIABIAAADQAEAAACABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAIgBAEIgEACIgGABQgFAAgDgCgACbAiQgEgFgBgKIAAgmQABgJAEgFQAEgFAJAAQAKAAAEAFQAEAFABAJIAAAmQgBAKgEAFQgEAFgKAAQgJAAgEgFgACkgaQgCACAAAEIAAAoQAAAEACACQAAABABAAQAAAAABAAQAAABABAAQABAAAAAAQABAAABAAQABAAAAgBQABAAAAAAQABAAAAgBQABgCABgEIAAgoQgBgEgBgCQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAgBAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAgADDAmIAAgMIALAAIAAAMgACFAmIgBgOIgPAAIgDAOIgKAAIAMhMIARAAIAMBMgACCAOIgGgmIgGAmIAMAAgAAvAmIgCgOIgOAAIgDAOIgLAAIANhMIARAAIAMBMgAArAOIgGgmIgFAmIALAAgAgVAmIAAgLIAWg2IgVAAIAAgLIAhAAIAAALIgWA2IAWAAIAAALgAgnAmIAAhMIALAAIAABMgAhMAmIAAhMIAMAAIAABBIATAAIAAALgAheAmIgDgOIgOAAIgCAOIgMAAIANhMIASAAIALBMgAhiAOIgGgmIgFAmIALAAgAihAmIAAhMIAhAAIAAALIgVAAIAAAWIAQAAIAAAJIgQAAIAAAXIAVAAIAAALgAi0AmIgBgCIAAgDIAAgFIAAgMQAAgFgCgCQgCgCgEAAIgEAAIAAAfIgMAAIAAhMIASAAQAJAAAFAFQAEAEgBAJIAAAGQAAAGgBAEQgCAEgEAAQAEACACAFQACAEAAAGIAAALIAAAFIABAFgAjBgDIAEAAQAEAAACgCQABgCABgEIAAgIQAAgEgBgCQgCgCgEAAIgFAAgADDgDIAAgLIALAAIAAALgABugtQABgEADgCQADgCACAAIAEABIADABIADABIADAAIABgDIAHAEQgCAEgDACQgCACgDgBIgEAAIgDgCIgCAAIgDAAIgDADg");
	this.shape.setTransform(70,-1.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo_7_Camada_2, null, null);


(lib.Símbolo_7_Camada_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKALQgDgCgCgIIgBgFQACgCAKgBIALgCIAFgCQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIACADQAAAAAAAAQAAABABAAQAAABAAAAQAAABgBABQgBAGgMADIgGAEIgDABIgEgBg");
	this.shape.setTransform(25.2775,29.4673,0.3421,0.3421);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FDE6DC").s().p("AgOAkIgIAAQgEAAgDgEQgEgEgEgMQgEgLAAgDQABgCACgDQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAAgCQABgCADgDQAEgCADAAIABABQgEgEADgFQABgEAEgDQAAgBABAAQABAAAAgBQABAAAAAAQABAAAAABIADACIAAgCIABgCIAEgDIAEgBIAKAGIgFADIAEAFQAEAGACAHQAAABAFABIAGABIAOgMQAFABgBAEIgIANQgGAMgEADIgUAMQgNAIgFAAIAAAAg");
	this.shape_1.setTransform(23.9194,30.5874,0.3421,0.3421);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgTA1QgOAAgIgKQgGgGgFgPQgFgPAAgHQACgLAJgGIAGgGIACgEQAHgQANgCIABgBQAIgFAHAAQAEAAAEACIADACQAEACATgFQARgEACADIAFAGIgSARIAIACQADABAFAKIAEAFQABABgCAEQgMAagLAJQghAXgPAAg");
	this.shape_2.setTransform(23.9038,30.5671,0.3421,0.3421);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E2A28D").s().p("AgJArIgHgDIgUgNQgCABgGgCQAOgVATgRQAVgUAXgKIALAJIgBAAIgCAEIgrAlQAAABACAPIgCAOQAAAFgFAAIgCAAg");
	this.shape_3.setTransform(8.1361,26.1037,0.3421,0.3421);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FDE6DC").s().p("Ag3AyQgDgBABgYIACgZQAAgBAOgIQASgJALgHQAMgIAMgQIALgNIAjAdQACABgYATQgYAUAAACIAAAiQgBAHgPAGQgDABADgIIADgJQAAgBgKgHQgKgGgEAAQgCAAgGAFIgHAIQgCACAAAPQAAADgGAEQgDgKgEgDg");
	this.shape_4.setTransform(7.6287,26.1077,0.3421,0.3421);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#020202").s().p("AhEBPQgDgDgCgJIgDgOQgCgEABgWIACgVQAAgJAGgLIAGgIIApgdQAkgbgDAEIADgDIgBgCQAAgBAGACQAGARAbATQAOAJAMAGQgGAAgGgCIgFgCIgDABIgGAFIgIAGQgLAPgNANQgCgBABALIADATQABAIgPAKQgLAJgKAEQgJADgBgHQgCgFADgHQACgEgCgBIgKgCQgFgBgFAKIgFAPQgBAEgIAEQgEACgDAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAg");
	this.shape_5.setTransform(7.8898,26.116,0.3421,0.3421);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#020202").s().p("AAYAPIgCgBIgEgBQgPAAgSgGQgMgEACgKIAGgKQALgCAIAEQAEACAIAHQADACAFgCQACgBABAAQAAAAABAAQABAAAAAAQAAAAAAABQACAHgCARQAAAAAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAg");
	this.shape_6.setTransform(24.6759,28.0188,0.342,0.342);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#020202").s().p("AgiAJIABgIQACgIALgEQATgJAIACIAOABQAMABABABQADAEgEABIgGABQgFAAgCACIgNAKQgKAKgGACQgMAEgEAAIgBAAQgHAAgBgKg");
	this.shape_7.setTransform(19.7773,28.4395,0.342,0.342);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#020202").s().p("AA4AfIgNgOQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBAAAAgBQgDgCgFAFQgKAMghADQgvAFgzgdQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgDgCAHgEQARgMAQgKQAfgTAYgDIAOACQANACADAFQAJAPADAAQAOACgBABIgFADQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAAAABQAKAFAAgDQAAgFADABIADAAQADAAADAEQAHAHALAWQAJALARAEIALAAQAHAAgCAFQAAACgbAEQgOAAgPgOg");
	this.shape_8.setTransform(15.0596,30.3297,0.342,0.342);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ACJHEQgLgDgBgHQgCgKABgNQACgKgBgCQgJgUgGgIQAFgRACgiQACgrgGgnQACgfgMgmQgNghAAgDIgHgZQgHgXgBgFQgBgPgLgQQgPgYgagDIgLAbQgLAdAAAFIgCAeQgCAaAEANQAEAOAGAcQAFAZABAIQADAaA0BNQAEAHALALQAJAJAEAIIABADIgKABQgBABgHgGQAAAAAAABQAAAAAAAAQAAABAAABQAAAAAAABIABAEQgDACgMAAIgSgBQgIgBgCgEQgEgQABgHQAAgDgmg4IgOgWQgNgUgMgPQgqgxACghQACgcgDgsIgHh6QAAgFgGgCIgHgDQgCgCgaAUQgaAUgGAHIgaAhQgYAigNAfQgkBXgcBMIgPArQgGAcADAoQAEAjgCADIABACQAFAMABAMQACAIgJAEQgBABgFgEQgEgEgBABQgCAAAAAHQgBAHgDAAQgPACgPgFIgNgGQAAgPAEgWIAChDQAAgKgDgVQgCgQACgHIAFgqIAEgnIAmhcIAZg8QAVg1gBgSQgFisAEgVQACgMARgeQAVgkACgGQACgFALgQQAJgPACgGQABgEgFgDQgGgDABgDQgCgYABgZQADgyASgCQA2gDAIBAIACAQIgEgBQgFgBgEACQgIAFgXAkIA5gHQA/gEAeAUQAEAFAMgGQAKgGAXgCQAagBANAJQAKgGAPgUQASgYAGgFQASgPAcAAQAhABALACQAMABAGAGQAMAKAIADQASAHAfgEIASgCIABAAQAeAAAIAUQAGAQABAIIABAGQALANgCAHQgBAEgDADIgDAFIgoAXQgoAWAAAIQACARgEAYQgGAjgPAfIgCAJQgCAMABAOQADBIgPApIgZA1QgRAjgIAoQgKAsgBASQAAAIADAIQAEALADAVQAGAegEASIgJAqQgCAYAMAdQAGANARAaIgGADIgIgNIACAQQgKAGgFgCIgHABIgMABQgBAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgEgCQgBADgDABQgGACgGAAIgJgBg");
	this.shape_9.setTransform(13.377,39.8748,0.342,0.342);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("ABzHWQgNgIgDgPQgEgRAEgRIgBgBIgEgIQgJAFgTAAIgUgCQgZgEgGgTQgDgNgCgLQgLgUgWgfIgCgCIgBgDQgJgSgaggQgwg5ADgrQACgegEgnIgGheIgbAVIgCACQgoAzgQAnQgrBqgVA4IgEALQgJAWgCANQgEAWADAfIACAkQAFAMABALIAAACQADANgGAMQgGALgNAGIgFADIgDAAQgHAHgJAAIgMABQgbAAgWgNIgNgIIABgPQAAgRADgXIADhAIgDgZQgDgXADgNQABgFAEgmQADggACgHIAVg0IARgpIAHgQQAlhZAAgRIgBgtQgEiGAEgTQADgSAZgrIAQgdIAKgUIAFgKQgDgGAAgHQgIhVAZgdQAMgNAQgBIAHAAQAaAAAUANQAfAVAHAxQAFANACALIAIAAQAoAAAiATQAUgJAcAAQAQAAALAEIAMgQQAQgWANgKQAYgRAhAAIADAAQAmABALABQASADALAKIACABQAFAFAGACQAJADAQAAIANAAIABgBIABAAQBEACANAiQAGAQACALQAPAWgGASQgCAJgFAGQgDAGgHAFIgUAMIgwAcQAAA5gaA1IAAAAQgBAIAAAOQADBOgQAtQgFANgNAaQgWAugJAoQgLAzABAKIAAAAIABACIAIAgQAHAlgFAaIgEAPQgFATAAAKQAAAPAJATQACAHASAcIAOAVIgcAUIgGAEIgDAAQgLAHgMAAIgGAAIgCAAIgLACIgHAAQgKACgIAAQgTAAgNgJgABYFEIgGhQQACgfgIgdQgIgYAAgDIgHgaQgHgYAAgFQgCgNgBgEQgFgNgQgLIgGARQgFARgBAGQgEAkAJAXQAEAMAHAjIAIAlQAKAYADADQAJASATAXQADADACAJg");
	this.shape_10.setTransform(13.3421,39.9084,0.342,0.342);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E7A449").s().p("AAyCkQACgOAEgCQAEgZAAgFQAAgFAFgGIAEgIQAFgEgCgFQgBgEACgIQACgJADgCQADgRACgDQAIgPAAgNQAAgEAFgIQAFgHAAgEIgFghQgEgZgFAEIgVAWQgPAQgFAAIgMgCQgIAAgDADQgGAHgMAJQgPALgEgBIgHgEQgEgBgCABQgCACADAEQADAFgBACIgLALQgLAOgFASQgBAJgIACQgQAFAKAMQAKANgKADQgFABgBABQgCACABADQACAEgKAFQgLAEgMgEQgPgFgbgUQgfgXgIgPIAEgKQAGgKAIAAQAHAAAFAEIAgAhQgCgIgIgOQgEgJADAAQACgBAdAgQAAAAAAABQAAAAgBAAQAAAAgBABQgBAAgBAAIgFACQAFAGAUAFQgBgEgPgTQgRgVgOgOQgEgFABgFQAAgCABAAQAAgBABgBQAAAAABAAQAAAAABABQAGAFAdAQQAeARABgDQAAgDgEgDIgJgEQgYgMAHgCQAFgBAGABIAIAAQAAAAAAAAQABAAgBgBQAAAAAAAAQgBgBgBgBQgEgDgFgBQgjgIADgDQABgBAQAEQAPAEAEgBQAEgCAAgEQAAgFgFgCQgBAAAAgBQAAAAAAAAQABAAABAAQABAAACAAQAHAAAFACQAIADAGgBQAIAAAAgEQAAgEADgDIAGgEQAHgFABgCQABgEgPgBQgTgCgGgDQgHgDAMgBIAgABQAUABgBgEQAAgDgIgIIgLgMIgJgMQgEgGAGAEIAUAWQAOAOABgFQAEgUgCgGQgBgFAEgEQAFgGALABQAuAFAAgHQAAgDgGgQQgFgNADACQAEADADgBQABgBAAAAQABAAAAgBQAAAAABgBQAAgBAAAAQAAgTAFAIQARAdADgLQACgFgFgVQgDgQADAEQAKAQACgHIAAgFQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAJgFAEgIQAOgegCAMQgBAIgGASQgFASgCACQgDACAAAFQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAQgCABgDAVQgDAWACAEIAKAeQAJAbAFAHQAjAtACAMQACAJACAcIAKAYIALAXQAGAfgJgGIgNgLQgHgFgDAFQgDAFgNgFQgNgFgBABIgdAGQggAJgSAVIABgNg");
	this.shape_11.setTransform(14.6345,20.7658,0.3421,0.3421);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#D1D2D3").s().p("AAGAQQgFgBgIgHIgIgGIgFgGQgFgIAFgCQAHgDAGADIAUAGIAGADQAFACAAACQAAAGgGAGQgFAGgFAAIgCgBg");
	this.shape_12.setTransform(27.1206,7.6894,0.3421,0.3421);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F1C872").s().p("AgwA/QgEgDgBgEQgBgEAEgBQAEgBAIgKQAIgJABgEQAFgLAIgIQAGgGABAAIACgJQADgTABgBQADgDAHgbIAGgMIAEgBIAGgBQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIgCAFIgEAIQgDAFAFADQAEACAFAAQAGgBAEABQANAEgEAGQgDAEAAACIABAJIABAGIAFAJQADAGgGAAQgMgBgFACIgNAGQgDACABAEIAIAPQADAGgEAEIgIAFQgDADgKgFIgQgIQgFgDAEAKQAFAOAAAEQgBAJgOADQgTgGgGgDg");
	this.shape_13.setTransform(26.2625,22.3611,0.3421,0.3421);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#E7A449").s().p("AgPASQgCgIgIgHIgIgEQgCgIALgMQALgNADACIADACQAEACAPgBQARAAAEAHQACAFgDAFQgMAIgFAHIgPAeIgCAAQgJAAgEgPg");
	this.shape_14.setTransform(26.2728,26.7137,0.3421,0.3421);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F1C872").s().p("AglAPQgHgPAOgNQAHgHAJgEQANgCAWAKIATALIgMAJQgMALAAAJQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgLAAgngKg");
	this.shape_15.setTransform(24.5628,25.8078,0.3421,0.3421);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#E7A449").s().p("AgSBCIgcgKIgCgFQgBgFAEgDQAQgMAGgOQABgDAHgHQAHgHADgGQACgFABgLQAAgKACgBIABgIQADgJADgDQAFgIAHgFQAGgEACgBQADADACAKQABAKABAAQAEAFAKAUIABAPQABAPgCAGQgBAGgEABQgFAAgCAEIgBAMQgBAHgEABQgFACgKAMIgLAOIgBAAQgEAAgRgGg");
	this.shape_16.setTransform(26.1403,22.6192,0.3421,0.3421);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAOAaIgMgSIgCgDIgDgCIgMAAIAAAXIgGAAIAAgzIAVAAIAKABQAFACABAEQADADgBAFQABAEgEAFQgEADgHAAIAEADIAPAVgAgPgCIAPAAIAGgBIAEgDIABgEQAAgEgCgDQgDgCgGAAIgPAAg");
	this.shape_17.setTransform(132.6043,40.4925,0.3421,0.3421);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgiAjQgOgPAAgUQAAgUAOgOQAOgOAUAAIAAAAQAVAAAOAOQAOAOAAAUQAAAUgOAPQgOAOgVABQgTAAgPgPgAgcgcQgNAMAAAQIABAAQAAARAMAMQAMANAQAAQASAAAMgNQAMgMAAgRQAAgQgNgMQgMgNgRAAIAAAAQgQAAgMANg");
	this.shape_18.setTransform(132.5103,40.4925,0.3421,0.3421);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAOAZIgMgRQAAgBAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBIgDgBIgMAAIAAAWIgGAAIgBgxIAWAAQAHgBADACQADAAADAEQACAEAAAEQAAAGgDADQgEADgHACQACAAACACIAGAHIAJANgAgPgCIAPAAIAGgBQABAAABgBQAAAAABAAQAAgBAAAAQABgBAAAAIABgFQAAgDgCgCQgEgDgFAAIgPAAg");
	this.shape_19.setTransform(26.0529,52.2089,0.3421,0.3421);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgiAjQgOgOAAgUIAAgBQAAgTAOgPQAPgPATAAIAAAAQAUAAAPAPQAPAPAAATQAAAVgPAOQgPAOgUAAQgUAAgOgOgAgdgdQgLANAAAQQAAARALANQANAMAQgBQASABAMgMQALgNABgRQgBgQgLgNQgMgMgSABQgQgBgNAMg");
	this.shape_20.setTransform(25.9588,52.2089,0.3421,0.3421);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F1C872").s().p("ACVCdIhPjMIhEAhQgPAKgTAPQgmAigRAgIgVApQgFAIgFgEIgrgWQgpgXAEgIQAHgGADgFQAIgOAIgHQAHgHAVgbQAKgLAWgWQAegdAHgCQAIgCAagOQAZgOAEgFIAcglQAdgiAOgEQAOgDArgDIAggDIAagEQAGgCADABQAEABgDAEQgNAUgJAaQgOArASAPIATgOIAJgIQAEgDABACIgJArQgHAyAGAfQADAlgBADQgIANAAACQACANgBATQgCAdgFAYQgFATgCACg");
	this.shape_21.setTransform(15.4283,19.8951,0.3421,0.3421);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#317C98").s().p("Ai8EiQgVABAEgOQADgLAKgHQAHgFATgaQAWgeAOgbQANgWBVg7QBSg6AAgCQACgGAPgnIAUgyQAFgLACgsQADgvgEgHQgDgGAPglQARgnAAgDQAAgHALgIQAKgJAKgDQAMgEADgJIAUAAQAVABgCAIQgCAMgPApQgOAqgRA5QgIAbghBKQgDAHgHAeQgJAbgIAFQgJAEgXAqIgVApQAGAPgtCFIg5AhQhhgMghACg");
	this.shape_22.setTransform(19.7176,41.8305,0.3421,0.3421);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#E7A449").s().p("AhgCOIADgcIANhAIACgaQABgXACgCIAPghQAWgjgCgBIgDgBQgDACgFAKIgXAoIgFAKQgDAGAAAFIgEAqIgPBgQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgNgEgFgKQAKgfAEgdQAKg/AHgOIAhg8IAOgYQAOgTAXgHIAHgCQAGgCAEADIAFACIgEABIgTAHQgOAHgCANIABABQABAAAAAAQABgBAAAAQAAAAABAAQAAgBAAAAIAKgMQALgJASgBIADADQADAHACAOIAFACQAFACAEgEQADgEAJgUIAKgSQABABgDAHQAAACAMgWQgDAOAGgDQAFgDADAEQAEAEgEAGIgJAMQgGAGABAEIAEgFQABgBABAAQAAgBABAAQAAAAAAABQABAAgBABIAAAGQABAHAFADIgFAEQgEADACABQACACAGgHIAHAHQAGAIgBAEQgZASgYAIIgBADQAAABABAAQAAABAAABQABAAAAAAQABABABAAQAFAAAPgHQAQgGAEgDIAJADIgOAEQgNAFAAABIACADQABABAGgBQAIgBAVgHQAEABAAACIgFACQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAABIANANQAEACAEAPQADAPgEAHIgaAkIgaAiIgIAIQgDADgEAAIgTgBQgBgCgLABIgLAAIgBgHIAEgEQAZgRAAgGIAAgJQABgEAEgEQACgCAFAAQADAAABgJQAAgKgCgSQAAgHgLgRQgLgJgIABIgDgBQAAAAAAAAQgBgBAAAAQAAAAABgBQAAAAABAAIAJgEQAGgCAAgBQAAgEgDABIgLAFQgJAFACAFQAAAAAAAAQAAAAAAAAQAAAAgBgBQAAAAgBAAIAQgwIADgHQgDAFgGgDIgCgBQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABIgPAzIgGAFQgEAEABAFIgHATQgQABgLgJQgHgGgCACQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAAAIgRAoIgGAJQgEAIAEALQADAHAFAJQADAFgCACIgNAJQgKAJAAAKIABAOIAAAFQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAIgEABIgIABQgFAAAAgCgAhnA1QgCABgBAFIAAAEQAAAGAEABQAEAAAEgCQADgBABgMQAAgEgEgCIgBAAQgDAAgFAEgAhmA/IACgHQADgCACAAQABAAAAABQABAAAAABQAAAAABAAQAAABgBABQAAAGgCACIgDAAQgEAAAAgDg");
	this.shape_23.setTransform(25.7683,21.7052,0.3421,0.3421);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#D1D2D3").s().p("AA9AGQhAgHgqAEIgKACQgLACAAgBQgJgGAcgCIApgDQAsgCAZAHQAMAHgJAAIgFgBg");
	this.shape_24.setTransform(26.5254,11.6811,0.3421,0.3421);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#D1D2D3").s().p("AgbArQgEgDgBgCQgBgEADgIIARgfIATgiIAEgDQAAgBABAAQAAAAABAAQAAAAAAAAQABABAAAAQADACAMAEQAJAGgHAEQgOAIADAGIAFAHQAAABAAAAQAAABAAABQAAAAAAABQgBAAgBABIgLAFQgJAGAAAEQgCALgFACQgIACABAGQABAEgGADIgFABIgFgBg");
	this.shape_25.setTransform(24.5113,9.2583,0.3421,0.3421);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#D1D2D3").s().p("AAAATQgNgNgEgGQgDgFgZgWQgDgCAIgEIAIgEQAOgDASACQAPACAJAEQABAEgGAHIgHAIQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIABABIAPAIQADADgDANQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIACACQAFAIAKAEQAHACgVAFQgNgFgSgQg");
	this.shape_26.setTransform(22.0551,10.9819,0.3421,0.3421);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#EDB564").s().p("AgNAlQgCgCgIAEIgDgBQgBAAAAAAQAAAAAAgBQAAAAAAAAQABAAABgBQAJgEAJgfQAPgKAUgeIgBAJQgCALgDAIIgGAMQgFAJAAAHQgBAEgHAIQgGAJgGACIgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBg");
	this.shape_27.setTransform(27.3278,27.0779,0.3421,0.3421);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F1C872").s().p("AgQAlIgGgSIAAgHQABgEgBgBIABgDIAIgUQAHgUACAAIAEAEQABABAVAJQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBABIgGAFIgEAFIgDAKIgFAHQgEAHAAABIgFAHQgJAMgCAAIAAAAg");
	this.shape_28.setTransform(24.4381,23.1636,0.3421,0.3421);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F1C872").s().p("AgHAjQgCgOgGgKIgIgIQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBQASgEATggQAAAAABABQAAABAAAAQAAABABAAQAAAAAAABIADgBQAAgBAAABQABAAAAAAQAAAAAAABQAAAAAAABQgBALgMAbQgKAYgEAGQAAAAAAABQgBAAAAABQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBg");
	this.shape_29.setTransform(27.1152,16.9375,0.3421,0.3421);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F1C872").s().p("AgbAgQgBgPADgGIAJgVQALgXAIgKIABAAQACACABAHIAGAGQAGAFADgBQAFgCABAFQAAAGgDAEIgOAYQgFAIgBgBQgBgCgJAIQgMAJgIAKIgCgNg");
	this.shape_30.setTransform(22.2892,14.9572,0.3421,0.3421);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#020202").s().p("AgeAHIAFgHQAFgHAEgCQACAAADgGQADgFABABQAAAAABAAQAAAAAAABQABAAAAABQAAABAAABQABADACABIALADQAKACABgBQAFgCACAEQAFALgBAFQgBACgKADQgLAEgKAAIgDAAQgUAAgGgNg");
	this.shape_31.setTransform(25.9419,15.0858,0.3421,0.3421);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FDE6DC").s().p("AACAxQgNgBgDgEQgDgDgHgCIgLgDQgGgDgNgTQgDgEABgLQABgKABgDQABgCAAggQAIgCANAIIAFAEIAIAGIASAFIARAFIAFAEQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAAJAEABQABABAAAAQAAAAABgBQAAAAAAAAQAAAAABgBIABgEIAAgJQgBgBAAgBQAAgBABAAQAAgBAAAAQABAAAAAAQACAAAHAKQAIAKADACQAKAEgEAEQgSAYgBAAQgIALgIAEQgFACgJAAIgGAAg");
	this.shape_32.setTransform(25.6866,14.5835,0.3421,0.3421);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F1C872").s().p("AgHBXQgpgZgGgOQgHgPAKgdQAFgPAPgcQAHgPADgWIADgYQABgEAEgCIAEgCQAAACASAVQATAUACADIAOAfQAMAfABAgQACAggNAZQgHANgHAGQgTgJgUgMg");
	this.shape_33.setTransform(28.82,18.7376,0.3421,0.3421);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#E2A28D").s().p("AgfAEQgQgVAEADIAKgVIADACQABACAAACQgCANAIAVQAHANAfgDQAMgBAOABQAGgBgFADQgIAFgTAIIgRAGQgOgKgPgWg");
	this.shape_34.setTransform(24.4959,16.4625,0.3421,0.3421);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FDE6DC").s().p("AgugSQADgTAJgUIAIgQQABAAAAAOQgBARAKAMQAMANAXgBQAOAAANgEQABAAABAAQABAAABAAQAAAAAAAAQAAAAAAABQgCADgOAFIgTAHQgKAEgHAEQgPALgGARQgKAbgNARQgGgrAGgxg");
	this.shape_35.setTransform(24.2639,17.754,0.3421,0.3421);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#E2A28D").s().p("AgEAJQgwgUgFgEIgJgMIAGAAQAKABATAJQBcABAGgCIgXAuIgwgTg");
	this.shape_36.setTransform(26.1327,13.8709,0.3421,0.3421);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgsLRQgLgGgCgLQgDgNADgTIAAgBIgMgTIgEAAIgBABQgJAFgUAAQgNAAgIgEIgEABQgKAEgNAAQgfAAgUgdIgGgJIAGgJIABgCIgDgCQgIgHAAgMQABgNALgOQAFgGAIgGIgBgCIAxgtIACgEQARglARgSQAVgWAGgJIgFgRQgJgZAAgIQgBgGADgOQAMhDgJgNIgCgBIgOgCIgPlPIAJgVQADgMAKgbQACgEAAgLQAAgRAMgMQAAgLAGgMIAAgDIAHgJQACgMAGgJQAAgHAEgLIABgGQABgMAIgGIAAgBIACgCQAAgJAEgPIgBgmIgEAEQgUAWgFAEQgKAGgRABIgWATIgRAKIgCACIgBABIgJAMIgJATIgFAOIgCAGIAAAGQAAANgLAJQgLASgFAAIgEADQgKAIgXABIgCAAQgKAAgQgIIgHAFIgCABIgBABQgGADgIAIQgHAJgEAHIgBAAIABAJQABANgNAUQgNASgMAFIgJACQgKAAgHgJIgCgFQgKAVgRAAQgIAAgGgFQgFgEABgGIABgLIgBgMQgGgPADgoQABgcASAAQAugUAPgUIACgDQgLgQAGgNQAFgLAUgPIAEgDIAHgJIASgTIABgHIABgEIACgDQAKgQAHgEIAEgCIApgpIABAAIAYgVQAOgGAFgCQAGgCAOgJQAQgKAFgFQAEgFAHgKQAOgVAagZQAOgMASgIQARgIAKAAIADABIAhACIAegEQAagDAHgCIAUgBQgYgXgKgOQgRgSgFgEQgKgEgBgLIgBgPQABgFAJgFQAUgIAKgBIAVAAQAGAAALAEIAQAEIAig6IAMgSQAIgIAKAAIAIgBIAJAAQAlAAAeAPQASAKAKAcQAHAWAGAoIA5AKQAYAEABAIQACAQgEAIQgCAHgIAGQgMAKgOAEQgVAHglACIgRAnQAIAKAeAaQAOAMAMAkQAMAiABAYQACBHgMAQIgGAJQgqA7gSANIAAAJQgBA9gNAWIgCAFIgBA6QgBAqgDAUQAAAHADAGIgGAxQgHAwgDALQgFATgGAmQgGAsACAaQABAlgCATQgSACgBgGIgBgpIAAgyQABgGgEgNQgEgMADgVQACgXAHgQIAJgRIAKgeQAGgXgGgBQgFgBgIAPIgIASQgCAEgBARIgDAOQgDAMgCADQgCAEgCAUQgDAVgBAFQgCAIgDAdQgDAdABAIQAAALgCBLQgBABgFAAIgKAAQgGgBAAgGQAIhQgBgCIgDgFQgCgCgDAHIgMAeIgKAcIgeAoIgEAGQgSApgQAUQACANgBAOQgBAKgHAgQgIAigEAKQgEAIgBAWQgBAVACAHQAGANAAALQAQARABANQABAJgHAJIgEAFQgIAKgNACIgDACIgEADIgDAAIgCABQgJAGgJAAIgFgBIgEABIgLABIgBABIgBAAIgDgBIgCABQgJACgHAAQgPAAgKgHg");
	this.shape_37.setTransform(18.7033,31.3644,0.3421,0.3421);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("ABkCRIgmABIgchUQgWgDgfgBQgbAAgSAEIgMAgIgQA0IgXgBIgWABIBCiSQAlhWAWg8IAOABIARgBQAWA8AjBWIAnBeIAPAjIAIASQgRgCgVAAgAg0AeQAXACAOgBQATAAATgBIgBgCIgjhcg");
	this.shape_38.setTransform(130.1413,49.3782,0.3421,0.3421);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAACRIgiABIADg0QABgqAAg0IgCh9QABgKgCgKIAiABIAigBIgDA0IgCBdIACB+IACAUQgPgBgTAAg");
	this.shape_39.setTransform(122.9233,49.3525,0.3421,0.3421);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("ABICSIgmABQgLgWgXgpQgcgzgRgaIACB3IACAUIgigBIgjABIADg0IABheIgDiSIBvAAQApABAWATQAXAVAAAjQAAAkgcAUQgQAMgYADQAPAcAaApIAPAZIAWAhIANATIgngBgAgth2IAABtIAMABQAXABAPgSQAOgRAAgcQAAgXgLgOQgMgNgWAAg");
	this.shape_40.setTransform(116.5947,49.3354,0.3421,0.3421);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AhzBvQgrgnAAhBQAAhGAsgsQAsgrBGAAQBJABArAnQAsAogBBAQAABHgsArQgsArhHAAQhHAAgsgogAhAhYQgZAkAAA7QAAA2AYAfQAZAgAoAAQApAAAZgjQAYgkAAg7QAAg2gYgfQgYgfgqgBQgoAAgYAjg");
	this.shape_41.setTransform(105.6396,49.2926,0.3421,0.3421);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAACTIgiABIAEkJIhNAFQACgIAAgJQAAgKgCgIQAOADAeAAIBHABQAYABAhgCQAbAAAQgCIAAAjQgHgCgbgCIgrgBIACEIQgPgBgSAAg");
	this.shape_42.setTransform(95.5649,49.2157,0.3421,0.3421);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgQCQIgjABIgeACIAEiTIgDiTIAiABIAjgBQgCAMgBAYIgCDkIBAgBIAigDIgBARIABASg");
	this.shape_43.setTransform(88.364,49.2841,0.3421,0.3421);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AhhB2QgfggAAg/IgDirIAiABIAjgBIgEA1QgBArAAA1IAAARQAAAyATAZQATAYAnAAQAoABAUgbQAVgcAAg0IgCieIAVABIAWgBIgEA0QgCAsAAA0IAAAIQAABGggAjQggAjhBAAQg/AAgfgfg");
	this.shape_44.setTransform(78.8197,49.2841,0.3421,0.3421);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("Ag0CTQgSgFgSgJIAHgaIAGgaIAJAAQAHAWAOAMQAOAKAWAAQAVABANgMQAPgNAAgSQAAgRgNgNQgNgMgjgRQgggPgRgUQgPgUAAgcQAAgoAbgaQAbgZAnAAQATAAARAEQAQAFATAKIgOApIgIABQgHgSgLgIQgLgIgUAAQgSAAgMALQgMAKAAARQAAAQAMAMQAMAMAhAQQAjAQAPAUQAQAWAAAdQAAApgeAZQgdAbgsAAQgTAAgTgEg");
	this.shape_45.setTransform(69.4808,49.1815,0.3421,0.3421);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("ABrCRIgTACQgug6hUhbIgzg3IAAA5IAABeIADA0IgSgBIgTABIADg1IAChdIgEiSIAVABIAUgBQAjAtBEBMIBLBQIgCjIIATABIASgBIgDA0IgCBeQABBeACA0g");
	this.shape_46.setTransform(60.1162,49.1558,0.3421,0.3421);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AAACXQhIAAgrgoQgrgoAAhAQAAhHAsgrQArgrBIAAQBHAAAsAnQAsAogBBBQAABGgsAsQgqArhGAAIgDAAgAhAhYQgYAigBA9QAAA2AYAfQAYAgApAAQApAAAZgjQAYgkAAg7QAAg2gYgfQgYgggqAAQgoAAgYAjg");
	this.shape_47.setTransform(48.4769,49.1134,0.3421,0.3421);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AhRBvQgtgnAAhBQABhHAtgrQAtgrBJAAQAZAAAXAEQAVAEAUAJIgLAwIgFABQgNgUgRgJQgTgKgWAAQgsAAgaAhQgbAiAAA4QAAA6AcAgQAbAiAvAAQAXAAARgIQATgHAQgQIAHADIgLAmQgUAJgSAEQgUAEgVAAQhJAAgtgog");
	this.shape_48.setTransform(37.7095,49.0874,0.3421,0.3421);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AABG6Qg4AAguACQAFhXADhVQAChqAAh0IAAmTQg7ABhIADQhNAFgZAFQAEgaAAgbQAAgagEgaQAjAFBgAEQBhAEBLAAIAsAAQBLAABggEQBhgEAigFQgEAWAAAeQAAAfAEAWQgYgFhNgFQhJgDg6gBIAAGTQAACXACBHQABBDAHBpQgtgCg5AAg");
	this.shape_49.setTransform(124.591,25.7314,0.3421,0.3421);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AlaFRQiEh3AAjDQAAjXCEiDQCEiDDWAAQDZAACDB3QCDB2AADEQAADWiDCDQiDCDjZAAQjXAAiDh2gAjFkKQhJBrAAC1QAACiBJBfQBKBfB7AAQB9AABKhrQBJhrAAi0QAAiihJhfQhKhgh9AAQh7AAhKBrg");
	this.shape_50.setTransform(96.5398,25.8597,0.3421,0.3421);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("Aj0FRQiJh3AAjCQAAjXCJiEQCJiDDeAAQBKAABFANQBDAOA5AZQgLAmgIAiQgFAWgJAzIgOABQgng6g2gdQg2gehCAAQiHAAhQBmQhQBlAACsQAACrBTBkQBUBlCNAAQBEAAA4gXQA4gYAygwIARAJQgMAhgGAXQgHAfgFAbQg2Aag+ANQg7AOg+AAQjfAAiIh2g");
	this.shape_51.setTransform(66.2823,25.8597,0.3421,0.3421);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AieG6Qg8gOgxgZQAPgyAHgcQAJglAHgqIAbgBQAXBGApAfQAqAgBEAAQA/AAAqgkQAqglAAg4QAAgzgmglQgmgjhug1Qhjgugvg9Qgug+AAhVQAAh1BQhOQBRhOB4AAQA5AAAyAOQAzANA4AeQgRArgGATQgJAZgLAnIgYABQgUg2gigYQgjgZg6AAQg3AAglAgQglAhAAAwQAAAzAlAjQAiAiBoAyQBnAxAxA/QAwBAAABXQAAB5haBRQhZBQiGAAQg3AAg6gNg");
	this.shape_52.setTransform(42.9691,25.8597,0.3421,0.3421);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo_7_Camada_1, null, null);


(lib.Cena_1_Camada_9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_9
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EFC672").s().p("A7jDlIAAnJIZQAAIAAHJgAX2BZQgMgNAAgXIAAhiQAAgXAMgMQALgNAWAAQAWAAAMANQALAMAAAXIAAATIgdAAIAAgVQAAgKgDgEQgFgFgHAAQgIAAgEAFQgDAEAAAKIAABmQAAALADAEQAEAEAIAAQAHAAAFgEQADgEAAgLIAAgjIgNAAIAAgaIAqAAIAAA7QAAAXgLANQgMAMgWABQgWgBgLgMgAQUBZQgLgMAAgXIAAiRIAeAAIAACTQgBAKAEAEQAFAEAHAAQAIAAADgEQAEgEAAgKIAAiTIAdAAIAACRQAAAXgMAMQgLANgWAAQgWAAgLgNgAOqBZQgLgNAAgXIAAgLIAcAAIAAANQAAALAEAEQAEAEAIAAQAHAAAEgEQAEgFABgKQgBgLgGgJQgFgJgKgIIgRgQQgJgIgFgLQgGgMAAgQQgBgXALgMQAMgNAWAAQAVAAAMANQALAMAAAXIAAAGIgcAAIAAgIQgBgKgEgEQgDgFgHAAQgIAAgDAFQgFAEAAAKQABAMAFAJQAGAIAJAIIASAQQAIAIAGAMQAGALAAAQQAAAXgLANQgMAMgVABQgXgBgLgMgACHBZQgLgNAAgXIAAhiQAAgXALgMQALgNAWAAQAWAAALANQAMAMAAAXIAAATIgdAAIAAgVQAAgKgEgEQgEgFgHAAQgHAAgFAFQgEAEAAAKIAABmQAAALAEAEQAFAEAHAAQAHAAAEgEQAEgEAAgLIAAgjIgNAAIAAgaIAqAAIAAA7QAAAXgMANQgLAMgWABQgWgBgLgMgAbHBjIAAgdIAdAAIAAAdgAaaBjIgGgiIgkAAIgGAiIgbAAIAfi+IAsAAIAeC+gAZzAnIAeAAIgPhggAXABjIgFgiIgkAAIgGAiIgcAAIAfi+IAsAAIAfC+gAWaAnIAdAAIgOhggAUlBjIgdi+IAeAAIAXCbIAXibIAcAAIgeC+gAS4BjIgEgiIglAAIgGAiIgbAAIAei+IAsAAIAfC+gASSAnIAdAAIgOhggANNBjIgGgiIgkAAIgFAiIgcAAIAfi+IAsAAIAeC+gAMnAnIAdAAIgPhggAK/BjIAAiiIgeAAIAAgcIBcAAIAAAcIggAAIAACigAJ1BjIgmiJIAACJIgbAAIAAi+IAmAAIAeByIAAhyIAbAAIAAC+gAIIBjIgGgiIgkAAIgGAiIgbAAIAfi+IAsAAIAeC+gAHhAnIAeAAIgPhggAGVBjIAAgFIgBgGIgBgMIAAgeQAAgNgFgGQgEgGgLABIgKAAIAABNIgeAAIAAi+IAtAAQAYAAAKALQALALAAAWIAAAPQgBAPgEAKQgFAIgKAFQALAFAFAKQAEALAAAPIAAAdIAAAMQABAGACAFgAF1gFIAMAAQAIAAAFgEQAFgFAAgLIAAgTQAAgKgEgFQgEgEgHAAIgPAAgAEqBjIgEgiIglAAIgFAiIgcAAIAei+IAsAAIAfC+gAEFAnIAcAAIgOhggAgQBjIAAi+IBRAAIAAAcIg0AAIAAA1IApAAIAAAaIgpAAIAAA4IA0AAIAAAbgAbKA5IgEiUIAeAAIgECUg");
	this.shape.setTransform(530.95,44.275);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(195).to({_off:false},0).to({_off:true},51).wait(29));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_5
	this.instance = new lib.Bitmap1();
	this.instance.parent = this;
	this.instance.setTransform(-9,-47,0.4866,0.4866);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(275));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D2F23").s().p("EglOAIbIAAw1MBKdAAAIAAQ1UgoNgBZgiQABZg");
	this.shape.setTransform(571.65,43.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0D2F23").s().p("EglOAIbIAAw1MBKdAAAIAAQ1g");
	this.shape_1.setTransform(571.65,43.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},274).wait(1));

}).prototype = p = new cjs.MovieClip();


(lib.Símbolo7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_2_obj_
	this.Camada_2 = new lib.Símbolo_7_Camada_2();
	this.Camada_2.name = "Camada_2";
	this.Camada_2.parent = this;
	this.Camada_2.setTransform(70,-1.9,1,1,0,0,0,70,-1.9);
	this.Camada_2.depth = 0;
	this.Camada_2.isAttachedToCamera = 0
	this.Camada_2.isAttachedToMask = 0
	this.Camada_2.layerDepth = 0
	this.Camada_2.layerIndex = 0
	this.Camada_2.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_2).wait(1));

	// Camada_1_obj_
	this.Camada_1 = new lib.Símbolo_7_Camada_1();
	this.Camada_1.name = "Camada_1";
	this.Camada_1.parent = this;
	this.Camada_1.setTransform(67.8,31.4,1,1,0,0,0,67.8,31.4);
	this.Camada_1.depth = 0;
	this.Camada_1.isAttachedToCamera = 0
	this.Camada_1.isAttachedToMask = 0
	this.Camada_1.layerDepth = 0
	this.Camada_1.layerIndex = 1
	this.Camada_1.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Símbolo7, new cjs.Rectangle(0,-7.2,135.7,63.5), null);


(lib.Cena_1_Camada_15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_15
	this.instance = new lib.Símbolo7();
	this.instance.parent = this;
	this.instance.setTransform(534.4,46.4,0.4553,0.4553,0,0,0,69.4,23.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(246).to({_off:false},0).wait(1).to({regX:67.8,regY:24.5,scaleX:0.5867,scaleY:0.5867,x:533.45,y:47,alpha:0.6563},0).wait(1).to({scaleX:0.7181,scaleY:0.7181,x:533.25,y:47.2,alpha:0.8457},0).wait(1).to({scaleX:0.8495,scaleY:0.8495,x:533,y:47.3,alpha:0.928},0).wait(1).to({scaleX:0.9809,scaleY:0.9809,x:532.8,y:47.5,alpha:0.9504},0).wait(15).to({alpha:0.9516},0).wait(1).to({alpha:0.9431},0).wait(1).to({alpha:0.923},0).wait(1).to({alpha:0.8887},0).wait(1).to({alpha:0.8362},0).wait(1).to({alpha:0.759},0).wait(1).to({alpha:0.6452},0).wait(1).to({alpha:0.4656},0).wait(1).to({alpha:0},0).wait(2));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_12
	this.instance = new lib.Símbolo9();
	this.instance.parent = this;
	this.instance.setTransform(525.75,51.25,0.4553,0.4553,0,0,0,183.2,46.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(60).to({_off:false},0).wait(1).to({regX:186.8,regY:42.8,scaleX:0.6003,scaleY:0.6003,x:527.9,y:49.25,alpha:0.5949},0).wait(1).to({scaleX:0.7453,scaleY:0.7453,x:528.4,y:48.75,alpha:0.7875},0).wait(1).to({scaleX:0.8902,scaleY:0.8902,x:528.95,y:48.25,alpha:0.8878},0).wait(1).to({scaleX:1.0352,scaleY:1.0352,x:529.5,y:47.8,alpha:0.9364},0).wait(1).to({scaleX:1.1802,scaleY:1.1802,x:529.95,y:47.35,alpha:0.9504},0).wait(10).to({alpha:0.9101},0).wait(1).to({alpha:0.7928},0).wait(1).to({alpha:0.6331},0).wait(1).to({alpha:0.4443},0).wait(1).to({alpha:0.2329},0).wait(1).to({alpha:0},0).wait(42));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_11
	this.instance = new lib.Símbolo8();
	this.instance.parent = this;
	this.instance.setTransform(536.1,53.1,0.4553,0.4553,0,0,0,180.6,31.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:176.7,regY:21.9,scaleX:0.5788,scaleY:0.5788,x:533.8,y:47.55,alpha:0.5949},0).wait(1).to({scaleX:0.7023,scaleY:0.7023,x:533.35,y:46.35,alpha:0.7875},0).wait(1).to({scaleX:0.8258,scaleY:0.8258,x:532.85,y:45.15,alpha:0.8878},0).wait(1).to({scaleX:0.9493,scaleY:0.9493,x:532.4,y:43.95,alpha:0.9364},0).wait(1).to({scaleX:1.0728,scaleY:1.0728,x:531.9,y:42.75,alpha:0.9504},0).wait(13).to({alpha:0.9456},0).wait(1).to({alpha:0.9044},0).wait(1).to({alpha:0.8088},0).wait(1).to({alpha:0.6161},0).wait(1).to({alpha:0},0).wait(38));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_10
	this.instance = new lib.Símbolo6();
	this.instance.parent = this;
	this.instance.setTransform(438,46.35,1,1,0,0,0,78,27.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(195).to({_off:false},0).to({_off:true},51).wait(29));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_7
	this.instance = new lib.Símbolo5();
	this.instance.parent = this;
	this.instance.setTransform(538.95,46.7,0.4553,0.4553,0,0,0,157,19.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(149).to({_off:false},0).wait(1).to({regX:153.2,regY:19.7,scaleX:0.5507,scaleY:0.5507,x:536.8,y:46.75,alpha:0.5467},0).wait(1).to({scaleX:0.6461,scaleY:0.6461,x:536.45,y:46.8,alpha:0.7371},0).wait(1).to({scaleX:0.7415,scaleY:0.7415,x:536.1,alpha:0.8457},0).wait(1).to({scaleX:0.837,scaleY:0.837,x:535.7,alpha:0.9087},0).wait(1).to({scaleX:0.9324,scaleY:0.9324,x:535.4,alpha:0.9409},0).wait(1).to({scaleX:1.0278,scaleY:1.0278,x:535,y:46.85,alpha:0.9504},0).wait(27).to({alpha:0.9517},0).wait(1).to({alpha:0.9444},0).wait(1).to({alpha:0.9284},0).wait(1).to({alpha:0.9033},0).wait(1).to({alpha:0.8687},0).wait(1).to({alpha:0.8242},0).wait(1).to({alpha:0.7693},0).wait(1).to({alpha:0.7034},0).wait(1).to({alpha:0.6257},0).wait(1).to({alpha:0.5352},0).wait(1).to({alpha:0.4306},0).wait(1).to({alpha:0.3099},0).wait(1).to({alpha:0.1697},0).wait(1).to({alpha:0},0).wait(14));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_6_Cópia = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_6_Cópia
	this.instance = new lib.Símbolo3();
	this.instance.parent = this;
	this.instance.setTransform(446.2,45.65,1,1,0,0,0,47.8,31.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(144).to({_off:false},0).wait(1).to({regX:44.6,regY:31.2,x:443,y:7.05},0).wait(1).to({y:-18.95},0).wait(1).to({y:-34.75},0).wait(1).to({y:-42.8},0).wait(1).to({y:-45.8},0).wait(1).to({y:-46.25},0).wait(1));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_6
	this.instance = new lib.Símbolo3();
	this.instance.parent = this;
	this.instance.setTransform(691.45,45.65,1,1,0,0,0,47.8,31.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(82).to({_off:false},0).wait(1).to({regX:44.6,regY:31.2,x:652.05,y:45.75,alpha:0.05},0).wait(1).to({x:617,alpha:0.1},0).wait(1).to({x:583.1,alpha:0.15},0).wait(1).to({x:550.35,alpha:0.2},0).wait(1).to({x:518.75,alpha:0.25},0).wait(1).to({x:488.15,alpha:0.3},0).wait(1).to({x:458.7,alpha:0.35},0).wait(1).to({x:443,alpha:0.4},0).wait(1).to({alpha:0.45},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.55},0).wait(1).to({alpha:0.6},0).wait(1).to({alpha:0.65},0).wait(1).to({alpha:0.7},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.8},0).wait(1).to({alpha:0.85},0).wait(1).to({alpha:0.9},0).wait(1).to({alpha:0.95},0).wait(1).to({alpha:1},0).wait(43));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_4_Cópia = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_4_Cópia
	this.instance = new lib.Símbolo4();
	this.instance.parent = this;
	this.instance.setTransform(592.1,45.3,1,1,0,0,0,88.3,31.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(144).to({_off:false},0).wait(1).to({y:6.6},0).wait(1).to({y:-19.4},0).wait(1).to({y:-35.2},0).wait(1).to({y:-43.25},0).wait(1).to({y:-46.25},0).wait(1).to({y:-46.7},0).wait(1));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_4
	this.instance = new lib.Símbolo4();
	this.instance.parent = this;
	this.instance.setTransform(816.9,45.3,1,1,0,0,0,88.3,31.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(85).to({_off:false},0).wait(1).to({x:782,alpha:0.0526},0).wait(1).to({x:748.3,alpha:0.1053},0).wait(1).to({x:715.7,alpha:0.1579},0).wait(1).to({x:684.3,alpha:0.2105},0).wait(1).to({x:654.05,alpha:0.2632},0).wait(1).to({x:624.85,alpha:0.3158},0).wait(1).to({x:596.7,alpha:0.3684},0).wait(1).to({x:592.1,alpha:0.4211},0).wait(1).to({alpha:0.4737},0).wait(1).to({alpha:0.5263},0).wait(1).to({alpha:0.5789},0).wait(1).to({alpha:0.6316},0).wait(1).to({alpha:0.6842},0).wait(1).to({alpha:0.7368},0).wait(1).to({alpha:0.7895},0).wait(1).to({alpha:0.8421},0).wait(1).to({alpha:0.8947},0).wait(1).to({alpha:0.9474},0).wait(1).to({alpha:1},0).wait(41));

}).prototype = p = new cjs.MovieClip();


(lib.Cena_1_Camada_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Camada_3
	this.instance = new lib.Símbolo2();
	this.instance.parent = this;
	this.instance.setTransform(541.3,47.4,0.4553,0.4553,0,0,0,177.3,33);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25).to({_off:false},0).wait(1).to({regX:166.2,regY:31.6,scaleX:0.5457,scaleY:0.5457,x:535.25,y:46.65,alpha:0.5467},0).wait(1).to({scaleX:0.6362,scaleY:0.6362,x:534.25,y:46.5,alpha:0.7371},0).wait(1).to({scaleX:0.7266,scaleY:0.7266,x:533.25,y:46.4,alpha:0.8457},0).wait(1).to({scaleX:0.817,scaleY:0.817,x:532.25,y:46.25,alpha:0.9087},0).wait(1).to({scaleX:0.9075,scaleY:0.9075,x:531.2,y:46.2,alpha:0.9409},0).wait(1).to({scaleX:0.9979,scaleY:0.9979,x:530.25,y:46.05,alpha:0.9504},0).wait(19).to({alpha:0.923},0).wait(1).to({alpha:0.759},0).wait(1).to({alpha:0},0).wait(42));

}).prototype = p = new cjs.MovieClip();


// stage content:
(lib._181016_728x90_curvas = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	this.___GetDepth___ = function(obj) {
		var depth = obj.depth;
		var cameraObj = this.___camera___instance;
		if(cameraObj && cameraObj.depth && obj.isAttachedToCamera)
		{
			depth += depth + cameraObj.depth;
		}
		return depth;
		}
	this.___needSorting___ = function() {
		for (var i = 0; i < this.getNumChildren() - 1; i++)
		{
			var prevDepth = this.___GetDepth___(this.getChildAt(i));
			var nextDepth = this.___GetDepth___(this.getChildAt(i + 1));
			if (prevDepth < nextDepth)
				return true;
		}
		return false;
	}
	this.___sortFunction___ = function(obj1, obj2) {
		return (this.exportRoot.___GetDepth___(obj2) - this.exportRoot.___GetDepth___(obj1));
	}
	this.on('tick', function (event){
		var curTimeline = event.currentTarget;
		if (curTimeline.___needSorting___()){
			this.sortChildren(curTimeline.___sortFunction___);
		}
	});

	// timeline functions:
	this.frame_274 = function() {
		this.___loopingOver___ = true;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(274).call(this.frame_274).wait(1));

	// Camada_15_obj_
	this.Camada_15 = new lib.Cena_1_Camada_15();
	this.Camada_15.name = "Camada_15";
	this.Camada_15.parent = this;
	this.Camada_15.depth = 0;
	this.Camada_15.isAttachedToCamera = 0
	this.Camada_15.isAttachedToMask = 0
	this.Camada_15.layerDepth = 0
	this.Camada_15.layerIndex = 0
	this.Camada_15.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_15).wait(247).to({regX:532.8,regY:47.5,x:532.8,y:47.5},0).wait(28));

	// Camada_10_obj_
	this.Camada_10 = new lib.Cena_1_Camada_10();
	this.Camada_10.name = "Camada_10";
	this.Camada_10.parent = this;
	this.Camada_10.depth = 0;
	this.Camada_10.isAttachedToCamera = 0
	this.Camada_10.isAttachedToMask = 0
	this.Camada_10.layerDepth = 0
	this.Camada_10.layerIndex = 1
	this.Camada_10.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_10).wait(275));

	// Camada_9_obj_
	this.Camada_9 = new lib.Cena_1_Camada_9();
	this.Camada_9.name = "Camada_9";
	this.Camada_9.parent = this;
	this.Camada_9.depth = 0;
	this.Camada_9.isAttachedToCamera = 0
	this.Camada_9.isAttachedToMask = 0
	this.Camada_9.layerDepth = 0
	this.Camada_9.layerIndex = 2
	this.Camada_9.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_9).wait(275));

	// Camada_7_obj_
	this.Camada_7 = new lib.Cena_1_Camada_7();
	this.Camada_7.name = "Camada_7";
	this.Camada_7.parent = this;
	this.Camada_7.depth = 0;
	this.Camada_7.isAttachedToCamera = 0
	this.Camada_7.isAttachedToMask = 0
	this.Camada_7.layerDepth = 0
	this.Camada_7.layerIndex = 3
	this.Camada_7.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_7).wait(150).to({regX:535.1,regY:46.9,x:535.1,y:46.9},0).wait(58).to({_off:true},1).wait(66));

	// Camada_4_Cópia_obj_
	this.Camada_4_Cópia = new lib.Cena_1_Camada_4_Cópia();
	this.Camada_4_Cópia.name = "Camada_4_Cópia";
	this.Camada_4_Cópia.parent = this;
	this.Camada_4_Cópia.depth = 0;
	this.Camada_4_Cópia.isAttachedToCamera = 0
	this.Camada_4_Cópia.isAttachedToMask = 0
	this.Camada_4_Cópia.layerDepth = 0
	this.Camada_4_Cópia.layerIndex = 4
	this.Camada_4_Cópia.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_4_Cópia).wait(145).to({regX:592.1,regY:-0.7,x:592.1,y:-0.7},0).wait(5).to({_off:true},1).wait(124));

	// Camada_6_Cópia_obj_
	this.Camada_6_Cópia = new lib.Cena_1_Camada_6_Cópia();
	this.Camada_6_Cópia.name = "Camada_6_Cópia";
	this.Camada_6_Cópia.parent = this;
	this.Camada_6_Cópia.depth = 0;
	this.Camada_6_Cópia.isAttachedToCamera = 0
	this.Camada_6_Cópia.isAttachedToMask = 0
	this.Camada_6_Cópia.layerDepth = 0
	this.Camada_6_Cópia.layerIndex = 5
	this.Camada_6_Cópia.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_6_Cópia).wait(145).to({regX:443,regY:-0.2,x:443,y:-0.2},0).wait(5).to({_off:true},1).wait(124));

	// Camada_4_obj_
	this.Camada_4 = new lib.Cena_1_Camada_4();
	this.Camada_4.name = "Camada_4";
	this.Camada_4.parent = this;
	this.Camada_4.depth = 0;
	this.Camada_4.isAttachedToCamera = 0
	this.Camada_4.isAttachedToMask = 0
	this.Camada_4.layerDepth = 0
	this.Camada_4.layerIndex = 6
	this.Camada_4.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_4).wait(86).to({regX:704.5,regY:45.3,x:704.5,y:45.3},0).wait(58).to({_off:true},1).wait(130));

	// Camada_6_obj_
	this.Camada_6 = new lib.Cena_1_Camada_6();
	this.Camada_6.name = "Camada_6";
	this.Camada_6.parent = this;
	this.Camada_6.depth = 0;
	this.Camada_6.isAttachedToCamera = 0
	this.Camada_6.isAttachedToMask = 0
	this.Camada_6.layerDepth = 0
	this.Camada_6.layerIndex = 7
	this.Camada_6.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_6).wait(83).to({regX:565.6,regY:45.8,x:565.6,y:45.8},0).wait(61).to({_off:true},1).wait(130));

	// Camada_12_obj_
	this.Camada_12 = new lib.Cena_1_Camada_12();
	this.Camada_12.name = "Camada_12";
	this.Camada_12.parent = this;
	this.Camada_12.depth = 0;
	this.Camada_12.isAttachedToCamera = 0
	this.Camada_12.isAttachedToMask = 0
	this.Camada_12.layerDepth = 0
	this.Camada_12.layerIndex = 8
	this.Camada_12.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_12).wait(61).to({regX:529.9,regY:47.4,x:529.9,y:47.4},0).wait(60).to({_off:true},1).wait(153));

	// Camada_3_obj_
	this.Camada_3 = new lib.Cena_1_Camada_3();
	this.Camada_3.name = "Camada_3";
	this.Camada_3.parent = this;
	this.Camada_3.depth = 0;
	this.Camada_3.isAttachedToCamera = 0
	this.Camada_3.isAttachedToMask = 0
	this.Camada_3.layerDepth = 0
	this.Camada_3.layerIndex = 9
	this.Camada_3.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_3).wait(26).to({regX:530.3,regY:46,x:530.3,y:46},0).wait(67).to({_off:true},1).wait(181));

	// Camada_11_obj_
	this.Camada_11 = new lib.Cena_1_Camada_11();
	this.Camada_11.name = "Camada_11";
	this.Camada_11.parent = this;
	this.Camada_11.setTransform(534.3,48.7,1,1,0,0,0,534.3,48.7);
	this.Camada_11.depth = 0;
	this.Camada_11.isAttachedToCamera = 0
	this.Camada_11.isAttachedToMask = 0
	this.Camada_11.layerDepth = 0
	this.Camada_11.layerIndex = 10
	this.Camada_11.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_11).wait(1).to({regX:531.9,regY:42.7,x:531.9,y:42.7},0).wait(58).to({_off:true},1).wait(215));

	// Camada_2_obj_
	this.Camada_2 = new lib.Cena_1_Camada_2();
	this.Camada_2.name = "Camada_2";
	this.Camada_2.parent = this;
	this.Camada_2.setTransform(571.6,43.4,1,1,0,0,0,571.6,43.4);
	this.Camada_2.depth = 0;
	this.Camada_2.isAttachedToCamera = 0
	this.Camada_2.isAttachedToMask = 0
	this.Camada_2.layerDepth = 0
	this.Camada_2.layerIndex = 11
	this.Camada_2.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_2).wait(275));

	// Camada_5_obj_
	this.Camada_5 = new lib.Cena_1_Camada_5();
	this.Camada_5.name = "Camada_5";
	this.Camada_5.parent = this;
	this.Camada_5.setTransform(234.3,51.1,1,1,0,0,0,234.3,51.1);
	this.Camada_5.depth = 0;
	this.Camada_5.isAttachedToCamera = 0
	this.Camada_5.isAttachedToMask = 0
	this.Camada_5.layerDepth = 0
	this.Camada_5.layerIndex = 12
	this.Camada_5.maskLayerName = 0

	this.timeline.addTween(cjs.Tween.get(this.Camada_5).wait(275));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(355,-33.4,550.1,182.5);
// library properties:
lib.properties = {
	id: 'F8FB13734FA88C4AA5077956713BB86E',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/181016_728x90_curvas_atlas_.png?1542138742774", id:"181016_728x90_curvas_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F8FB13734FA88C4AA5077956713BB86E'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


// Layer depth API : 

AdobeAn.Layer = new function() {
	this.getLayerZDepth = function(timeline, layerName)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline." + layerName + ".depth; else 0;";
		return eval(script);
	}
	this.setLayerZDepth = function(timeline, layerName, zDepth)
	{
		const MAX_zDepth = 10000;
		const MIN_zDepth = -5000;
		if(zDepth > MAX_zDepth)
			zDepth = MAX_zDepth;
		else if(zDepth < MIN_zDepth)
			zDepth = MIN_zDepth;
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline." + layerName + ".depth = " + zDepth + ";";
		eval(script);
	}
	this.removeLayer = function(timeline, layerName)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		var script = "if(timeline." + layerName + ") timeline.removeChild(timeline." + layerName + ");";
		eval(script);
	}
	this.addNewLayer = function(timeline, layerName, zDepth)
	{
		if(layerName === "Camera")
		layerName = "___camera___instance";
		zDepth = typeof zDepth !== 'undefined' ? zDepth : 0;
		var layer = new createjs.MovieClip();
		layer.name = layerName;
		layer.depth = zDepth;
		layer.layerIndex = 0;
		timeline.addChild(layer);
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;